CREATE TABLE users (id CHAR(36) PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE candidate_profiles (
  id CHAR(36) PRIMARY KEY, user_id CHAR(36) NULL, version INT NOT NULL DEFAULT 1,
  profile_json JSON NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_candidate_profiles_user (user_id), FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE candidate_profile_versions (id CHAR(36) PRIMARY KEY, candidate_profile_id CHAR(36) NOT NULL, version INT NOT NULL, profile_json JSON NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_profile_version (candidate_profile_id, version), FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profiles(id));
CREATE TABLE job_sources (id CHAR(36) PRIMARY KEY, name VARCHAR(100) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, config_json JSON NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_job_sources_name (name));
CREATE TABLE jobs (id CHAR(36) PRIMARY KEY, source_id CHAR(36) NULL, external_id VARCHAR(255) NULL, company VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, location VARCHAR(255) NULL, application_url TEXT NOT NULL, url_hash CHAR(64) NOT NULL, fingerprint CHAR(64) NOT NULL, raw_description MEDIUMTEXT NULL, status VARCHAR(32) NOT NULL DEFAULT 'DISCOVERED', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_jobs_fingerprint (fingerprint), UNIQUE KEY uq_jobs_source_external (source_id, external_id), INDEX idx_jobs_source_external (source_id, external_id), INDEX idx_jobs_company (company), INDEX idx_jobs_url_hash (url_hash), FOREIGN KEY (source_id) REFERENCES job_sources(id));
CREATE TABLE job_requirements (id CHAR(36) PRIMARY KEY, job_id CHAR(36) NOT NULL, kind VARCHAR(32) NOT NULL, value TEXT NOT NULL, required BOOLEAN NOT NULL DEFAULT FALSE, FOREIGN KEY (job_id) REFERENCES jobs(id), INDEX idx_job_requirements_job (job_id));
CREATE TABLE job_matches (id CHAR(36) PRIMARY KEY, job_id CHAR(36) NOT NULL, candidate_profile_version INT NOT NULL, score DECIMAL(5,2) NOT NULL, analysis_json JSON NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (job_id) REFERENCES jobs(id), INDEX idx_job_matches_score (score));
CREATE TABLE resumes (id CHAR(36) PRIMARY KEY, job_id CHAR(36) NOT NULL, application_id CHAR(36) NULL, candidate_profile_version INT NOT NULL, path TEXT NOT NULL, sha256 CHAR(64) NOT NULL, prompt_version VARCHAR(100) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (job_id) REFERENCES jobs(id), INDEX idx_resumes_application (application_id));
CREATE TABLE cover_letters (id CHAR(36) PRIMARY KEY, job_id CHAR(36) NOT NULL, application_id CHAR(36) NULL, path TEXT NOT NULL, sha256 CHAR(64) NOT NULL, prompt_version VARCHAR(100) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (job_id) REFERENCES jobs(id), INDEX idx_cover_letters_application (application_id));
CREATE TABLE applications (id CHAR(36) PRIMARY KEY, job_id CHAR(36) NOT NULL, status VARCHAR(32) NOT NULL, application_url TEXT NOT NULL, error_message TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_applications_job (job_id), INDEX idx_applications_status (status), INDEX idx_applications_created (created_at), FOREIGN KEY (job_id) REFERENCES jobs(id));
CREATE TABLE application_fields (id CHAR(36) PRIMARY KEY, application_id CHAR(36) NOT NULL, field_name VARCHAR(255) NOT NULL, value_status VARCHAR(32) NOT NULL, FOREIGN KEY (application_id) REFERENCES applications(id), INDEX idx_application_fields_application (application_id));
CREATE TABLE application_questions (id CHAR(36) PRIMARY KEY, application_id CHAR(36) NOT NULL, question TEXT NOT NULL, answer_status VARCHAR(32) NOT NULL, FOREIGN KEY (application_id) REFERENCES applications(id), INDEX idx_application_questions_application (application_id));
CREATE TABLE application_events (id CHAR(36) PRIMARY KEY, application_id CHAR(36) NOT NULL, event_type VARCHAR(100) NOT NULL, status VARCHAR(32) NOT NULL, detail_json JSON NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (application_id) REFERENCES applications(id), INDEX idx_application_events_application (application_id));
CREATE TABLE notifications (id CHAR(36) PRIMARY KEY, application_id CHAR(36) NULL, type VARCHAR(100) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_notifications_status (status));
CREATE TABLE audit_logs (id CHAR(36) PRIMARY KEY, job_id CHAR(36) NULL, application_id CHAR(36) NULL, event_type VARCHAR(100) NOT NULL, status VARCHAR(32) NOT NULL, detail_json JSON NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_audit_logs_application (application_id));
CREATE TABLE browser_sessions (id CHAR(36) PRIMARY KEY, application_id CHAR(36) NOT NULL, state VARCHAR(32) NOT NULL, last_url TEXT NULL, screenshot_path TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (application_id) REFERENCES applications(id));
CREATE TABLE search_runs (id CHAR(36) PRIMARY KEY, source_id CHAR(36) NULL, status VARCHAR(32) NOT NULL, started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, finished_at TIMESTAMP NULL, FOREIGN KEY (source_id) REFERENCES job_sources(id));
ALTER TABLE resumes ADD CONSTRAINT fk_resumes_application FOREIGN KEY (application_id) REFERENCES applications(id);
ALTER TABLE cover_letters ADD CONSTRAINT fk_cover_letters_application FOREIGN KEY (application_id) REFERENCES applications(id);
